version: '2.1'
services:
  squidex_redis:
    image: redis:alpine
    ports: 
      - "6379:6379"
    labels:
      NAME: "squidex_redis"
  squidex_mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    labels:
      NAME: "squidex_mongo"
  squidex_squidex:
    image: "squidex/squidex:latest"
    ports:
      - "5000:80"
    environment:
      - "URLS__BASEURL=${SQUIDEX_BASE_URL}"
      - "EVENTSTORE__CONSUME=true"
      - "EVENTSTORE__MONGODB__CONFIGURATION=mongodb://squidex_mongo"
      - "PUBSUB__TYPE=redis"
      - "PUBSUB__REDIS__CONFIGURATION=squidex_redis:6379,resolveDns=1"
      - "STORE__MONGODB__CONFIGURATION=mongodb://squidex_mongo"
      - "IDENTITY__KEYSSTORE__TYPE=redis"
      - "IDENTITY__KEYSSTORE__REDIS__CONFIGURATION=squidex_redis:6379,resolveDns=true"
      - "VIRTUAL_HOST=${SQUIDEX_DOMAIN}"
    depends_on:
      squidex_redis:
        condition: service_started
      squidex_mongo:
        condition: service_started
    labels:
      NAME: "squidex_squidex"
    restart: "always"
  squidex_proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro    
    depends_on:
      - "squidex_squidex"
    labels:
      NAME: "squidex_proxy"